### PR TITLE
Basic setup

### PR DESCRIPTION
**Pull request by rnou112**
Converted existing Medtech heart website to Nuxt based app.

### CODE REVIEW

**Comment by LIN810116** [comment]
Hi @rnou112 ,

All looks good to me. just one suggestion for the future.
In some .vue files, I can see you also embedded the javascript and CSS code there.  I think it would be good to separate the JavaScript and CSS code into separate .js and .css files from the .vue files.

@PrasadBabarendaGamage  I think we can merge this PR if you are also happy with it?

**Comment by LIN810116** [comment]
@rnou112, Can you please also convert the draft PR to a normal PR if it is ready to be merged?

**Comment by rnou112** [comment]
@LIN810116 I use CSS specific to the particular Vue page/component in it's file and keep the styles that are commonly used through out  in a separate files in assets folder. This was the practice we were following in 12 Labours front end app, so kind of using the same here. But, thanks for the suggestion, I will further explore on this how its best done in Nuxt apps. Moreover, if I manage to get some time and use Vuetify styles in their replacement, then most of these styles would be non-existent.
But kindly mention about the places where you suggest that JS code should be separate from the Vue file.

**Comment by rnou112** [comment]
In Nuxt, we maintain external JS or JS code that is used as helpers/used at multiple places in Plugins folder. So, I will be maintaining the code for ECG/LVP graphs and Models or anything else that is being reused at multiple places in Plugins. Apart from that, there is page/component specific few lines of code that are executing at relevant Vue hooks, and that would stay on the same page/component. 
Yes, the CSS thing is something that is more of a preference/choice, we can keep separate CSS files for each component provided we have a separate folder for each(which I am not using at the moment ). Lets look into these further in Nuxt/Vue documentation to check the best practice to do that.

**Comment by LIN810116** [comment]
Yup, sounds good to me. just have a look and make sure we are following the breast practices

**Pull request merged**
